dict_industry = {
    170: "Crop Production",
    180: "Animal Production and Aquaculture",
    190: "Forestry Except Logging",
    270: "Logging",
    280: "Fishing, Hunting and Trapping",
    290: "Support Activities For Agriculture and Forestry",
    370: "Oil and Gas Extraction",
    380: "Coal Mining",
    390: "Metal Ore Mining",
    470: "Nonmetallic Mineral Mining and Quarrying",
    490: "Support Activities For Mining",
    570: "Electric Power Generation, Transmission and Distribution",
    580: "Natural Gas Distribution",
    590: "Electric and Gas, and Other Combinations",
    670: "Water, Steam, Air Conditioning, and Irrigation Systems",
    680: "Sewage Treatment Facilities",
    690: "Not Specified Utilities",
    770: "Construction",
    1070: "Animal Food, Grain and Oilseed Milling",
    1080: "Sugar and Confectionery Products",
    1090: "Fruit and Vegetable Preserving and Specialty Foods",
    1170: "Dairy Products",
    1180: "Animal Slaughtering and Processing",
    1190: "Retail Bakeries",
    1270: "Bakeries and Tortilla, Except Retail Bakeries",
    1280: "Seafood and Other Miscellaneous Foods, N.E.C.",
    1290: "Not Specified Food Industries",
    1370: "Beverage",
    1390: "Tobacco",
    1470: "Fiber, Yarn, and Thread Mills",
    1480: "Fabric Mills, Except Knitting Mills",
    1490: "Textile and Fabric Finishing and Fabric Coating Mills",
    1570: "Carpet and Rug Mills",
    1590: "Textile Product Mills, Except Carpet and Rug",
    1670: "Knitting Fabric Mills, and Apparel Knitting Mills",
    1691: "Cut and Sew, and Apparel Accessories and Other Apparel",
    1770: "Footwear",
    1790: "Leather and Hide Tanning and Finishing, and Other Leather and Allied Products",
    1870: "Pulp, Paper, and Paperboard Mills",
    1880: "Paperboard Container",
    1890: "Miscellaneous Paper and Pulp Products",
    1990: "Printing and Related Support Activities",
    2070: "Petroleum Refining",
    2090: "Miscellaneous Petroleum and Coal Products",
    2170: "Resin, Synthetic Rubber, and Fibers and Filaments",
    2180: "Agricultural Chemicals",
    2190: "Pharmaceuticals and Medicines",
    2270: "Paint, Coating, and Adhesives",
    2280: "Soap, Cleaning Compound, and Cosmetics",
    2290: "Industrial and Miscellaneous Chemicals",
    2370: "Plastics Products",
    2380: "Tires",
    2390: "Rubber Products, Except Tires",
    2470: "Pottery, Ceramics, and Plumbing Fixture Manufacturing",
    2480: "Clay Building Material and Refractories",
    2490: "Glass and Glass Products",
    2570: "Cement, Concrete, Lime, and Gypsum Products",
    2590: "Miscellaneous Nonmetallic Mineral Products",
    2670: "Iron and Steel Mills and Steel Products",
    2680: "Aluminum Production and Processing",
    2690: "Nonferrous Metal, Except Aluminum, Production and Processing",
    2770: "-Foundries",
    2780: "Metal Forgings and Stampings",
    2790: "Cutlery and Hand Tools",
    2870: "Structural Metals, and Boiler, Tank, and Shipping Containers",
    2880: "Machine Shops; Turned Products; Screws, Nuts and Bolts",
    2890: "Coating, Engraving, Heat Treating and Allied Activities",
    2970: "Ordnance",
    2980: "Miscellaneous Fabricated Metal Products",
    2990: "Not Specified Metal Industries",
    3070: "Agricultural Implements",
    3080: "Construction, and Mining and Oil and Gas Field Machinery",
    3095: "Commercial and Service Industry Machinery",
    3170: "Metalworking Machinery",
    3180: "Engine, Turbine, and Power Transmission Equipment",
    3291: "Machinery N.E.C. or Not Specified",
    3365: "Computer and Peripheral Equipment",
    3370: "Communications, and Audio and Video Equipment",
    3380: "Navigational, Measuring, Electromedical, and Control Instruments",
    3390: "Electronic Components and Products, N.E.C.",
    3470: "Household Appliances",
    3490: "Electric Lighting and Electrical Equipment Manufacturing",
    3570: "Motor Vehicles and Motor Vehicle Equipment",
    3580: "Aircraft and Parts",
    3590: "Aerospace Products and Parts",
    3670: "Railroad Rolling Stock",
    3680: "Ship and Boat Building",
    3690: "Other Transportation Equipment",
    3770: "Sawmills and Wood Preservation",
    3780: "Veneer, Plywood, and Engineered Wood Products",
    3790: "Prefabricated Wood Buildings and Mobile Homes",
    3875: "Miscellaneous Wood Products",
    3895: "Furniture and Related Products",
    3960: "Medical Equipment and Supplies",
    3970: "Sporting and Athletic Goods, and Doll, Toy, and Game Manufacturing",
    3980: "Miscellaneous Manufacturing, N.E.C.",
    3990: "Not Specified Manufacturing Industries",
    4070: "Motor Vehicle and Motor Vehicle Parts and Supplies Merchant Wholesalers",
    4080: "Furniture and Home Furnishing Merchant Wholesalers",
    4090: "Lumber and Other Construction Materials Merchant Wholesalers",
    4170: "Professional and Commercial Equipment and Supplies Merchant Wholesalers",
    4180: "Metals and Minerals, Except Petroleum, Merchant Wholesalers",
    4195: "Household Appliances and Electrical and Electronic Goods Merchant Wholesalers",
    4265: "Hardware, and Plumbing and Heating Equipment, and Supplies Merchant Wholesalers",
    4270: "Machinery, Equipment, and Supplies Merchant Wholesalers",
    4280: "Recyclable Material Merchant Wholesalers",
    4290: "Miscellaneous Durable Goods Merchant Wholesalers",
    4370: "Paper and Paper Products Merchant Wholesalers",
    4380: "Drugs, Sundries, and Chemical and Allied Products Merchant Wholesalers",
    4390: "Apparel, Piece Goods, and Notions Merchant Wholesalers",
    4470: "Grocery and Related Product Merchant Wholesalers",
    4480: "Farm Product Raw Material Merchant Wholesalers",
    4490: "Petroleum and Petroleum Products Merchant Wholesalers",
    4560: "Alcoholic Beverages Merchant Wholesalers",
    4570: "Farm Supplies Merchant Wholesalers",
    4580: "Miscellaneous Nondurable Goods Merchant Wholesalers",
    4585: "Wholesale Electronic Markets and Agents and Brokers",
    4590: "Not Specified Wholesale Trade",
    4670: "Automobile Dealers",
    4680: "Other Motor Vehicle Dealers",
    4690: "Automotive Parts, Accessories, and Tire Stores",
    4770: "Furniture and Home Furnishings Stores",
    4780: "Household Appliance Stores",
    4795: "Electronics Stores",
    4870: "Building Material and Supplies Dealers",
    4880: "Hardware Stores",
    4890: "Lawn and Garden Equipment and Supplies Stores",
    4971: "Supermarkets and Other Grocery (Except Convenience) Stores",
    4972: "Convenience Stores",
    4980: "Specialty Food Stores",
    4990: "Beer, Wine, and Liquor Stores",
    5070: "Pharmacies and Drug Stores",
    5080: "Health and Personal Care, Except Drug, Stores",
    5090: "Gasoline Stations",
    5170: "Clothing Stores",
    5180: "Shoe Stores",
    5190: "Jewelry, Luggage, and Leather Goods Stores",
    5275: "Sporting Goods, and Hobby and Toy Stores",
    5280: "Sewing, Needlework, and Piece Goods Stores",
    5295: "Musical Instrument and Supplies Stores",
    5370: "Book Stores and News Dealers",
    5381: "Department Stores",
    5391: "General Merchandise Stores, Including Warehouse Clubs and Supercenters",
    5470: "Florists",
    5480: "Office Supplies and Stationery Stores",
    5490: "Used Merchandise Stores",
    5570: "Gift, Novelty, and Souvenir Shops",
    5580: "Miscellaneous Retail Stores",
    5593: "Electronic Shopping and Mail-Order Houses",
    5670: "Vending Machine Operators",
    5680: "Fuel Dealers",
    5690: "Other Direct Selling Establishments",
    5790: "Not Specified Retail Trade",
    6070: "Air Transportation",
    6080: "Rail Transportation",
    6090: "Water Transportation",
    6170: "Truck Transportation",
    6180: "Bus Service and Urban Transit",
    6190: "Taxi and Limousine Service",
    6270: "Pipeline Transportation",
    6280: "Scenic and Sightseeing Transportation",
    6290: "Services Incidental To Transportation",
    6370: "Postal Service",
    6380: "Couriers and Messengers",
    6390: "Warehousing and Storage",
    6470: "Newspaper Publishers",
    6480: "Periodical, Book, and Directory Publishers",
    6490: "Software Publishers",
    6570: "Motion Picture and Video Industries",
    6590: "Sound Recording Industries",
    6670: "Broadcasting, Except Internet",
    6672: "Internet Publishing and Broadcasting and Web Search Portals",
    6680: "Wired Telecommunications Carriers",
    6690: "Telecommunications, Except Wired Telecommunications Carriers",
    6695: "Data Processing, Hosting, and Related Services",
    6770: "Libraries and Archives",
    6780: "Other Information Services",
    6870: "Banking and Related Activities",
    6880: "Savings Institutions, Including Credit Unions",
    6890: "Nondepository Credit and Related Activities",
    6970: "Securities, Commodities, Funds, Trusts, and Other Financial Investments",
    6991: "Insurance Carriers",
    6992: "Agencies, Brokerage, and Other Insurance Related Activates",
    7071: "Lessors Of Real Estate, and Offices Of Real Estate Agents and Brokers",
    7072: "Real Estate Property Managers, Appraisers, and Other Activities Related To Real Estates",
    7080: "Automotive Equipment Rental and Leasing",
    7181: "Other Consumer Goods Rental",
    7190: "Commercial, Industrial, and Other Intangible Assets Rental and Leasing",
    7270: "Legal Services",
    7280: "Accounting, Tax Preparation, Bookkeeping, and Payroll Services",
    7290: "Architectural, Engineering, and Related Services",
    7370: "Specialized Design Services",
    7380: "Computer Systems Design and Related Services",
    7390: "Management, Scientific, and Technical Consulting Services",
    7460: "Scientific Research and Development Services",
    7470: "Advertising, Public Relations, and Related Services",
    7480: "Veterinary Services",
    7490: "Other Professional, Scientific, and Technical Services",
    7570: "Management Of Companies and Enterprises",
    7580: "Employment Services",
    7590: "Business Support Services",
    7670: "Travel Arrangements and Reservation Services",
    7680: "Investigation and Security Services",
    7690: "Services To Buildings and Dwellings",
    7770: "Landscaping Services",
    7780: "Other Administrative and Other Support Services",
    7790: "Waste Management and Remediation Services",
    7860: "Elementary and Secondary Schools",
    7870: "Colleges, Universities, and Professional Schools, Including Junior Colleges",
    7880: "Business, Technical, and Trade Schools and Training",
    7890: "Other Schools and Instruction, and Educational Support Services",
    7970: "Offices Of Physicians",
    7980: "Offices Of Dentists",
    7990: "Offices Of Chiropractors",
    8070: "Offices Of Optometrists",
    8080: "Offices Of Other Health Practitioners",
    8090: "Outpatient Care Centers",
    8170: "Home Health Care Services",
    8180: "Other Health Care Services",
    8191: "General Medical and Surgical Hospitals, and Specialty Hospitals",
    8192: "Psychiatric and Substance Abuse Hospitals",
    8270: "Nursing Care Facilities (Skilled Nursing Facilities)",
    8290: "Residential Care Facilities, Except Skilled Nursing Facilities",
    8370: "Individual and Family Services",
    8380: "Community Food and Housing, and Emergency Services",
    8390: "Vocational Rehabilitation Services",
    8470: "Child Day Care Services",
    8561: "Performing Arts Companies",
    8562: "Spectator Sports",
    8563: "Promoters and Managers For Artists, Athletes, Entertainers, and Other Public Figures",
    8564: "Independent Artists, Writers, and Performers",
    8570: "Museums, Art Galleries, Historical Sites, and Similar Institutions",
    8580: "Bowling Centers",
    8590: "Other Amusement, Gambling, and Recreation Industries",
    8660: "Traveler Accommodation",
    8670: "Recreational Vehicle Parks and Camps, Rooming and Boarding Houses, Dormitories, and Workers Camps",
    8680: "Restaurants and Other Food Services",
    8690: "Drinking Places, Alcoholic Beverages",
    8770: "Automotive Repair and Maintenance",
    8780: "Car Washes",
    8790: "Electronic and Precision Equipment Repair and Maintenance",
    8870: "Commercial and Industrial Machinery and Equipment Repair and Maintenance",
    8891: "Personal and Household Goods Repair and Maintenance",
    8970: "Barber Shops",
    8980: "Beauty Salons",
    8990: "Nail Salons and Other Personal Care Services",
    9070: "Drycleaning and Laundry Services",
    9080: "Funeral Homes, Cemeteries and Crematories",
    9090: "Other Personal Services",
    9160: "Religious Organizations",
    9170: "Civic, Social, Advocacy Organizations, and Grantmaking and Giving Services",
    9180: "Labor Unions",
    9190: "Business, Professional, Political, and Similar Organizations",
    9290: "Private Households",
    9370: "Executive Offices and Legislative Bodies",
    9380: "Public Finance Activities",
    9390: "Other General Government and Support",
    9470: "Justice, Public Order, and Safety Activities",
    9480: "Administration Of Human Resource Programs",
    9490: "Administration Of Environmental Quality and Housing Programs",
    9570: "Administration Of Economic Programs and Space Research",
    9590: "National Security and International Affairs",
    9670: "U.S. Army",
    9680: "U.S. Air Force",
    9690: "U.S. Navy",
    9770: "U.S. Marines",
    9780: "U.S. Coast Guard",
    9790: "U.S. Armed Forces, Branch Not Specified",
    9870: "Military Reserves or National Guard",
}

dict_sector = {
    170: "Agriculture, Forestry, Fishing, and Hunting",
    180: "Agriculture, Forestry, Fishing, and Hunting",
    190: "Agriculture, Forestry, Fishing, and Hunting",
    270: "Agriculture, Forestry, Fishing, and Hunting",
    280: "Agriculture, Forestry, Fishing, and Hunting",
    290: "Agriculture, Forestry, Fishing, and Hunting",
    370: "Mining, Quarrying, and Oil and Gas Extraction",
    380: "Mining, Quarrying, and Oil and Gas Extraction",
    390: "Mining, Quarrying, and Oil and Gas Extraction",
    470: "Mining, Quarrying, and Oil and Gas Extraction",
    490: "Mining, Quarrying, and Oil and Gas Extraction",
    570: "Transportation, Warehousing, and Utilities",
    580: "Transportation, Warehousing, and Utilities",
    590: "Transportation, Warehousing, and Utilities",
    670: "Transportation, Warehousing, and Utilities",
    680: "Transportation, Warehousing, and Utilities",
    690: "Transportation, Warehousing, and Utilities",
    770: "Construction",
    1070: "Manufacturing",
    1080: "Manufacturing",
    1090: "Manufacturing",
    1170: "Manufacturing",
    1180: "Manufacturing",
    1190: "Manufacturing",
    1270: "Manufacturing",
    1280: "Manufacturing",
    1290: "Manufacturing",
    1370: "Manufacturing",
    1390: "Manufacturing",
    1470: "Manufacturing",
    1480: "Manufacturing",
    1490: "Manufacturing",
    1570: "Manufacturing",
    1590: "Manufacturing",
    1670: "Manufacturing",
    1691: "Manufacturing",
    1770: "Manufacturing",
    1790: "Manufacturing",
    1870: "Manufacturing",
    1880: "Manufacturing",
    1890: "Manufacturing",
    1990: "Manufacturing",
    2070: "Manufacturing",
    2090: "Manufacturing",
    2170: "Manufacturing",
    2180: "Manufacturing",
    2190: "Manufacturing",
    2270: "Manufacturing",
    2280: "Manufacturing",
    2290: "Manufacturing",
    2370: "Manufacturing",
    2380: "Manufacturing",
    2390: "Manufacturing",
    2470: "Manufacturing",
    2480: "Manufacturing",
    2490: "Manufacturing",
    2570: "Manufacturing",
    2590: "Manufacturing",
    2670: "Manufacturing",
    2680: "Manufacturing",
    2690: "Manufacturing",
    2770: "Manufacturing",
    2780: "Manufacturing",
    2790: "Manufacturing",
    2870: "Manufacturing",
    2880: "Manufacturing",
    2890: "Manufacturing",
    2970: "Manufacturing",
    2980: "Manufacturing",
    2990: "Manufacturing",
    3070: "Manufacturing",
    3080: "Manufacturing",
    3095: "Manufacturing",
    3170: "Manufacturing",
    3180: "Manufacturing",
    3291: "Manufacturing",
    3365: "Manufacturing",
    3370: "Manufacturing",
    3380: "Manufacturing",
    3390: "Manufacturing",
    3470: "Manufacturing",
    3490: "Manufacturing",
    3570: "Manufacturing",
    3580: "Manufacturing",
    3590: "Manufacturing",
    3670: "Manufacturing",
    3680: "Manufacturing",
    3690: "Manufacturing",
    3770: "Manufacturing",
    3780: "Manufacturing",
    3790: "Manufacturing",
    3875: "Manufacturing",
    3895: "Manufacturing",
    3960: "Manufacturing",
    3970: "Manufacturing",
    3980: "Manufacturing",
    3990: "Manufacturing",
    4070: "Wholesale Trade",
    4080: "Wholesale Trade",
    4090: "Wholesale Trade",
    4170: "Wholesale Trade",
    4180: "Wholesale Trade",
    4195: "Wholesale Trade",
    4265: "Wholesale Trade",
    4270: "Wholesale Trade",
    4280: "Wholesale Trade",
    4290: "Wholesale Trade",
    4370: "Wholesale Trade",
    4380: "Wholesale Trade",
    4390: "Wholesale Trade",
    4470: "Wholesale Trade",
    4480: "Wholesale Trade",
    4490: "Wholesale Trade",
    4560: "Wholesale Trade",
    4570: "Wholesale Trade",
    4580: "Wholesale Trade",
    4585: "Wholesale Trade",
    4590: "Wholesale Trade",
    4670: "Retail Trade",
    4680: "Retail Trade",
    4690: "Retail Trade",
    4770: "Retail Trade",
    4780: "Retail Trade",
    4795: "Retail Trade",
    4870: "Retail Trade",
    4880: "Retail Trade",
    4890: "Retail Trade",
    4971: "Retail Trade",
    4972: "Retail Trade",
    4980: "Retail Trade",
    4990: "Retail Trade",
    5070: "Retail Trade",
    5080: "Retail Trade",
    5090: "Retail Trade",
    5170: "Retail Trade",
    5180: "Retail Trade",
    5190: "Retail Trade",
    5275: "Retail Trade",
    5280: "Retail Trade",
    5295: "Retail Trade",
    5370: "Retail Trade",
    5381: "Retail Trade",
    5391: "Retail Trade",
    5470: "Retail Trade",
    5480: "Retail Trade",
    5490: "Retail Trade",
    5570: "Retail Trade",
    5580: "Retail Trade",
    5593: "Retail Trade",
    5670: "Retail Trade",
    5680: "Retail Trade",
    5690: "Retail Trade",
    5790: "Retail Trade",
    6070: "Transportation, Warehousing, and Utilities",
    6080: "Transportation, Warehousing, and Utilities",
    6090: "Transportation, Warehousing, and Utilities",
    6170: "Transportation, Warehousing, and Utilities",
    6180: "Transportation, Warehousing, and Utilities",
    6190: "Transportation, Warehousing, and Utilities",
    6270: "Transportation, Warehousing, and Utilities",
    6280: "Transportation, Warehousing, and Utilities",
    6290: "Transportation, Warehousing, and Utilities",
    6370: "Transportation, Warehousing, and Utilities",
    6380: "Transportation, Warehousing, and Utilities",
    6390: "Transportation, Warehousing, and Utilities",
    6470: "Information",
    6480: "Information",
    6490: "Information",
    6570: "Information",
    6590: "Information",
    6670: "Information",
    6672: "Information",
    6680: "Information",
    6690: "Information",
    6695: "Information",
    6770: "Information",
    6780: "Information",
    6870: "Finance, Insurance, and Real Estate",
    6880: "Finance, Insurance, and Real Estate",
    6890: "Finance, Insurance, and Real Estate",
    6970: "Finance, Insurance, and Real Estate",
    6991: "Finance, Insurance, and Real Estate",
    6992: "Finance, Insurance, and Real Estate",
    7071: "Finance, Insurance, and Real Estate",
    7072: "Finance, Insurance, and Real Estate",
    7080: "Finance, Insurance, and Real Estate",
    7181: "Finance, Insurance, and Real Estate",
    7190: "Finance, Insurance, and Real Estate",
    7270: "Professional, Scientific, and Technical Services",
    7280: "Professional, Scientific, and Technical Services",
    7290: "Professional, Scientific, and Technical Services",
    7370: "Professional, Scientific, and Technical Services",
    7380: "Professional, Scientific, and Technical Services",
    7390: "Professional, Scientific, and Technical Services",
    7460: "Professional, Scientific, and Technical Services",
    7470: "Professional, Scientific, and Technical Services",
    7480: "Professional, Scientific, and Technical Services",
    7490: "Professional, Scientific, and Technical Services",
    7570: "Management of Companies and Enterprises",
    7580: "Administrative and support and waste management services",
    7590: "Administrative and support and waste management services",
    7670: "Administrative and support and waste management services",
    7680: "Administrative and support and waste management services",
    7690: "Administrative and support and waste management services",
    7770: "Administrative and support and waste management services",
    7780: "Administrative and support and waste management services",
    7790: "Administrative and support and waste management services",
    7860: "Educational Services",
    7870: "Educational Services",
    7880: "Educational Services",
    7890: "Educational Services",
    7970: "Health Care and Social Assistance",
    7980: "Health Care and Social Assistance",
    7990: "Health Care and Social Assistance",
    8070: "Health Care and Social Assistance",
    8080: "Health Care and Social Assistance",
    8090: "Health Care and Social Assistance",
    8170: "Health Care and Social Assistance",
    8180: "Health Care and Social Assistance",
    8191: "Health Care and Social Assistance",
    8192: "Health Care and Social Assistance",
    8270: "Health Care and Social Assistance",
    8290: "Health Care and Social Assistance",
    8370: "Health Care and Social Assistance",
    8380: "Health Care and Social Assistance",
    8390: "Health Care and Social Assistance",
    8470: "Health Care and Social Assistance",
    8561: "Arts, Entertainment, and Recreation",
    8562: "Arts, Entertainment, and Recreation",
    8563: "Arts, Entertainment, and Recreation",
    8564: "Arts, Entertainment, and Recreation",
    8570: "Arts, Entertainment, and Recreation",
    8580: "Arts, Entertainment, and Recreation",
    8590: "Arts, Entertainment, and Recreation",
    8660: "Accommodation and Food Services",
    8670: "Accommodation and Food Services",
    8680: "Accommodation and Food Services",
    8690: "Accommodation and Food Services",
    8770: "Other Services, Except Public Administration",
    8780: "Other Services, Except Public Administration",
    8790: "Other Services, Except Public Administration",
    8870: "Other Services, Except Public Administration",
    8891: "Other Services, Except Public Administration",
    8970: "Other Services, Except Public Administration",
    8980: "Other Services, Except Public Administration",
    8990: "Other Services, Except Public Administration",
    9070: "Other Services, Except Public Administration",
    9080: "Other Services, Except Public Administration",
    9090: "Other Services, Except Public Administration",
    9160: "Other Services, Except Public Administration",
    9170: "Other Services, Except Public Administration",
    9180: "Other Services, Except Public Administration",
    9190: "Other Services, Except Public Administration",
    9290: "Other Services, Except Public Administration",
    9370: "Public Administration",
    9380: "Public Administration",
    9390: "Public Administration",
    9470: "Public Administration",
    9480: "Public Administration",
    9490: "Public Administration",
    9570: "Public Administration",
    9590: "Public Administration",
    9670: "Military",
    9680: "Military",
    9690: "Military",
    9770: "Military",
    9780: "Military",
    9790: "Military",
    9870: "Military",
}
